version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cgp-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: icmr_cgp
    volumes:
      - cgp-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cgp-redis
    ports:
      - '6379:6379'
    volumes:
      - cgp-redisdata:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: cgp-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - cgp-esdata:/usr/share/elasticsearch/data

volumes:
  cgp-pgdata:
  cgp-redisdata:
  cgp-esdata:
